name: Event Sync and Analysis

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-and-analyze:
    runs-on: ubuntu-latest
    
    env:
      VITE_EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run event sync
        run: node scripts/sync-events.js
        
      - name: Run event analysis
        run: node scripts/analyze-events.js